// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     version.avsc
 */

package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/container"
)

type Version struct {
	App    string
	Number string
}

func DeserializeVersion(r io.Reader) (*Version, error) {
	return readVersion(r)
}

func NewVersionWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &Version{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func NewVersion() *Version {
	v := &Version{}

	return v
}

func (r *Version) Schema() string {
	return "{\"fields\":[{\"name\":\"App\",\"type\":\"string\"},{\"name\":\"Number\",\"type\":\"string\"}],\"name\":\"Version\",\"type\":\"record\"}"
}

func (r *Version) Serialize(w io.Writer) error {
	return writeVersion(r, w)
}
